[build]
	command = "npm run build"
	publish = "build"
[build.environment]
    PUBLIC_SANITY_DATASET="production"
    PUBLIC_SANITY_PROJECT_ID="m60p6rsb"
    MEDUSA_BACKEND_URL="http://localhost:9000"
    API_URL="http://localhost:5000"
    MONGO_URI="mongodb+srv://theobbb:d7E0vTDITY0QFMZe@cluster0.cyfvzya.mongodb.net/marisol"
    MONGO_DB="marisol"